# Site settings
title: OpenKAI
email: kai.yan@labromance.com
url: http://www.openkai.xyz
description: "Open Kinetic AI: an open source framework for intelligent Robots"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: LabRomance Inc.

# Build settings
markdown: kramdown
permalink: pretty

#theme: jekyll-theme-cayman
